# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6f7782e045552ca5d93da49d8cc72cd56dd36f02d1011e8fcacda9c41d8ccebc0b46edf40b0653e2f041befb00331ee848abac7799aed5b6635ce346240f4e

test:
  secret_key_base: 5691d9ba61220d0553280f700c0262627f11c6a3b9907e6774eb6675dfce16ddebd1c6eb219ea47c6d79c55b8af00cd668c8dd13f3c726341067bfb76026cbad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
